# This Makefile includes examples on how you can use the scripts
conf-many-certs:
	./config-many-certificates.sh \
		'github.com,andresmunozit,am@andresmunozit.com' \
		'github.com,acount1,user@account1.com' \
		'bitbucket.com,account2,user@gmail.com'
clean-ssh-config-backups:
	./clean-ssh-config-backups.sh
update-remote:
	./update-remote-host-name.sh
show-pubs:
	./show-pubs.sh
