# This Makefile includes examples on how you can use the scripts
conf-many-certs:
	./config-many-certificates.sh \
		'github.com,andresmunozit,am@andresmunozit.com' \
		'github.com,yalochat,andres.munoz@yalochat.com'
clean-ssh-config-backups:
	./clean-ssh-config-backups.sh
update-remote:
	./update-remote-host-name.sh